pipeline {
    agent none
    stages {
        stage('Run Tests') {
            parallel {
                stage('Test On Windows') {
                    agent any
                    steps {
                        echo "test"
                    }
                    
                }
                stage('Test On Linux') {
                    agent any
                    steps {
                        echo "test-2"
                    }
                    
                }
            }
        }

        stage('DeployStage'){
            steps{
                echo "test"
            }
        }

        stage('deploy Tests') {
            parallel {
                stage('Test On Windows') {
                    agent any
                    steps {
                        echo "test"
                    }
                    
                }
                stage('Test On Linux') {
                    agent any
                    steps {
                        echo "test-2"
                    }
                    
                }
            }
        }
        stage('Deploytest'){
            steps{
                echo "test"
            }
        }

    }
}