pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo "Building the project..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing..."
            }
        }
        stage('Test-1') {
            steps {
                echo "Retesting the project..."
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the project..." 
            }
        }
                stage('Deploy-2') {
            steps {
                echo "Deploying again..." 
            }
        }
    }
}
