pipeline{
    agent any

    stages{
        stage('GIT-CHECKOUT'){
            steps{
                git url:https://github.com/Meghanas581/ms2001.git, branch:'production'
            }
        }
    }
