pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Meghanas581/ms2001.git', branch: 'jenkins'
            }
        }
    }
}
