pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'production',
                    url: 'https://github.com/Meghanas581/ms2001.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t my-project:latest Web-page'
            }
        }

        stage('Deploy Container') {
            steps {
                sh '''
                docker rm -f my-web || true
                docker run -d -p 8081:80 --name my-project my-project:latest
                '''
            }
        }
    }

    post {
        success {
            echo '🎉 Deployment Successful!'
        }
        failure {
            echo '❌ Deployment Failed!'
        }
    }
}
