pipeline{
    agent any

    parameters{
        string[name: 'ENV',defaultvalue: 'prod',description: 'This is to test....']
        }

    stages{
        stage'Build'{
            steps{
                sh ...
                
                ...

            }
        } 
    }       
}    
