pipeline {
    agent any

    parameters {
        string(name: 'ENV', defaultValue: 'production', description: 'This is to test....')
    }

    stages {
        stage('Build') {
            steps {
                sh '''
                    echo "This is the build stage"
                    echo "Selected environment: ${ENV}"
                '''
            }
        }
    }
}
