pipeline {
    agent any

    stages {

        stage('Build-stage') {
            stages {
                stage('checking the code') {
                    steps {
                        sh "echo 'Hello world'"
                    }
                }

                stage('testing the code') {
                    steps {
                        sh "echo 'Hello world'"
                    }
                }
            }
        }

        stage('deploying the one more env') {
            stages {
                stage('deploy to dev') {
                    steps {
                        sh 'echo "testing in dev"'
                    }
                }
            }
        }
    }
}
